<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eventPatternLanguage" nsURI="http://www.bme.hu/mit/incquery/cep/dsl/EventPatternLanguage"
    nsPrefix="eventPatternLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="EventModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usages" upperBound="-1"
        eType="#//Usage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//ModelElements" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IQUsage" eSuperTypes="#//Usage"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventSourceUsage" eSuperTypes="#//Usage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElements">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//ModelElements"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAtomicEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//TypedParameterList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicEvent" eSuperTypes="#//AbstractAtomicEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticBindings" upperBound="-1"
        eType="#//StaticBinding" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IQPatternEvent" eSuperTypes="#//AbstractAtomicEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iqpattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeType" eType="#//IQPatternChangeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEvent" eSuperTypes="#//Event">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//EventParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complexEventExpressions"
        upperBound="-1" eType="#//ComplexEventExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//ModelElements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" unique="false"
        upperBound="-1" eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="ecore:EClass ../../../../../../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IQPatternChangeType">
    <eLiterals name="FOUND" literal="FOUND"/>
    <eLiterals name="LOST" value="1" literal="LOST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//TypedParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//EventTypedParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTypedParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//TypedParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingRule" eType="#//StaticBindingRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticBindingRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RangeFilter" eSuperTypes="#//StaticBindingRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//Range"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenOpen" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenClosed" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClosedClosed" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClosedOpen" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericFilter" eSuperTypes="#//StaticBindingRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralFilter" eSuperTypes="#//StaticBindingRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEventExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FollowsExpression" eSuperTypes="#//ComplexEventExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstEvent" upperBound="-1"
        eType="#//EventTypedParameterWithMultiplicity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//EventWithFollowsOperator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventWithFollowsOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" eType="#//FollowsOperator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//FollowerEventStructure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FollowsOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="FollowsOperatorNoTW" eSuperTypes="#//FollowsOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="FollowsOperatorViaTW" eSuperTypes="#//FollowsOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timewindow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FollowerEventStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="BranchExpression" eSuperTypes="#//FollowerEventStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//EventTypedParameterWithMultiplicity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTypedParameterWithMultiplicity"
      eSuperTypes="#//FollowerEventStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" eType="#//EventTypedParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//PatternCallParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternCallParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//PatternCallParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternCallParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//ModelElements">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapter" upperBound="-1"
        eType="#//Adapter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
