/*
* generated by Xtext
*/
package hu.bme.mit.incquery.cep.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.incquery.cep.dsl.services.EventPatternLanguageGrammarAccess;

public class EventPatternLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EventPatternLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.incquery.cep.dsl.parser.antlr.internal.InternalEventPatternLanguageParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.incquery.cep.dsl.parser.antlr.internal.InternalEventPatternLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "EventModel";
	}
	
	public EventPatternLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EventPatternLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
