/*
* generated by Xtext
*/
package hu.bme.mit.incquery.cep.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EventPatternLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/incquery/cep/dsl/parser/antlr/internal/InternalEventPatternLanguage.tokens");
	}
}
