/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.cep.dsl.ui.contentassist

import hu.bme.mit.incquery.cep.dsl.ui.contentassist.AbstractEventPatternLanguageProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EventPatternLanguageProposalProvider extends AbstractEventPatternLanguageProposalProvider {
}
