/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.srct;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SrctRuntimeModule extends hu.bme.mit.incquery.srct.AbstractSrctRuntimeModule {

}
