/**
 *
 * $Id$
 */
package hu.bme.mit.incquery.cep.metamodels.cep.validation;

import hu.bme.mit.incquery.cep.metamodels.cep.EventPattern;

/**
 * A sample validator interface for {@link hu.bme.mit.incquery.cep.metamodels.cep.ComplexEventPattern}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComplexEventPatternValidator {
    boolean validate();

    boolean validateCompositionEvents(EventPattern value);
}
