/**
 *
 * $Id$
 */
package hu.bme.mit.incquery.cep.metamodels.cep.validation;

import hu.bme.mit.incquery.cep.metamodels.cep.IEventSource;

/**
 * A sample validator interface for {@link hu.bme.mit.incquery.cep.metamodels.cep.Event}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EventValidator {
    boolean validate();

    boolean validateType(String value);
    boolean validateTimestamp(long value);
    boolean validateSource(IEventSource value);
}
