<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eventPatternLanguage" nsURI="http://www.bme.hu/mit/incquery/cep/dsl/EventPatternLanguage"
    nsPrefix="eventPatternLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="EventModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packagedModel" eType="#//PackagedModel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PackagedModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usages" upperBound="-1"
        eType="#//Usage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//ModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericUsage" eSuperTypes="#//Usage"/>
  <eClassifiers xsi:type="ecore:EClass" name="PatternUsage" eSuperTypes="#//Usage"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventPattern" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" eType="#//TypedParameterList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAtomicEventPattern" eSuperTypes="#//EventPattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicEventPattern" eSuperTypes="#//AbstractAtomicEventPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticBindings" eType="ecore:EClass ../../../../../../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IQPatternEventPattern" eSuperTypes="#//AbstractAtomicEventPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iqPatternRef" eType="#//ParametrizedIncQueryPatternReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iqChangeType" eType="#//IQPatternChangeType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEventPattern" eSuperTypes="#//EventPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="complexEventExpression"
        eType="#//ComplexEventExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPatterns" unique="false"
        upperBound="-1" eType="#//EventPattern"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionHandler" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="ecore:EClass ../../../../../../../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IQPatternChangeType">
    <eLiterals name="NEW_MATCH_FOUND" literal="NEW_MATCH_FOUND"/>
    <eLiterals name="EXISTING_MATCH_LOST" value="1" literal="EXISTING_MATCH_LOST"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//TypedParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypedParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass ../../../../../../../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventPatternParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//EventTypedParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTypedParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//EventPattern"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParametrizedIncQueryPatternReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iqpattern" eType="ecore:EClass ../../../../../../../../org.eclipse.incquery.patternlanguage/src-gen/org/eclipse/incquery/patternlanguage/PatternLanguage.ecore#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//PatternCallParameterList"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Multiplicity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Timewindow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventTypedParameterWithMultiplicity"
      eSuperTypes="#//FollowerEventStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPattern" eType="#//EventPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//PatternCallParameterList"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternCallParameterList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//PatternCallParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternCallParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexEventExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="AugmentedExpression" eSuperTypes="#//ComplexEventExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedExpression" eSuperTypes="#//AugmentedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="timewindow" eType="#//Timewindow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityExpression" eSuperTypes="#//AugmentedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimedMultiplicityExpression" eSuperTypes="#//AugmentedExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="multiplicity" eType="#//Multiplicity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timewindow" eType="#//Timewindow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//ComplexEventExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPatterns" upperBound="-1"
        eType="#//EventTypedParameterWithMultiplicity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FollowsExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="followerExpressions" upperBound="-1"
        eType="#//FollowerExpression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FollowerExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="followsOperator" eType="#//FollowsOperator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPattern" eType="#//FollowerEventStructure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FollowerEventStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="InnerBranchExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//BranchExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BranchExpression" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="FollowsOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="FollowsOperatorNoTW" eSuperTypes="#//FollowsOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaticBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//TypedParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingRule" eType="#//StaticBindingRule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticBindingRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="RangeFilter" eSuperTypes="#//StaticBindingRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//Range"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpenOpen" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="OpenClosed" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClosedClosed" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClosedOpen" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericFilter" eSuperTypes="#//StaticBindingRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralFilter" eSuperTypes="#//StaticBindingRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapter" upperBound="-1"
        eType="#//Adapter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
