/*
* generated by Xtext
*/
package hu.bme.mit.incquery.vedl.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractEdlJavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(hu.bme.mit.incquery.vedl.edl.EdlPackage.eINSTANCE);
		return result;
	}

}
