/*
* generated by Xtext
*/
package hu.bme.mit.incquery.srct;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SrctUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return hu.bme.mit.incquery.srct.ui.internal.SrctActivator.getInstance().getInjector("hu.bme.mit.incquery.srct.Srct");
	}
	
}
