/**
 *
 * $Id$
 */
package hu.bme.mit.incquery.cep.casestudy.transaction.validation;

import hu.bme.mit.incquery.cep.casestudy.transaction.Component;
import hu.bme.mit.incquery.cep.casestudy.transaction.CompoundTransactionEvent;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hu.bme.mit.incquery.cep.casestudy.transaction.TransactionModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransactionModelValidator {
	boolean validate();

	boolean validateLatestComponentEvent(Component value);
	boolean validateLatestCompoundEvent(CompoundTransactionEvent value);

	boolean validateCompoundTransactionEvents(CompoundTransactionEvent value);

	boolean validateCompoundTransactionEvents(EList<CompoundTransactionEvent> value);
}
