/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.vedl.ui;

import hu.bme.mit.incquery.vedl.ui.syntaxcoloring.EdlAntlrTokenToAttributeIdMapper;
import hu.bme.mit.incquery.vedl.ui.syntaxcoloring.EdlHighlightingConfiguration;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EdlUiModule extends
		hu.bme.mit.incquery.vedl.ui.AbstractEdlUiModule {
	public EdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return EdlHighlightingConfiguration.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return EdlAntlrTokenToAttributeIdMapper.class;
	}
}
