/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.vedl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EdlUiModule extends hu.bme.mit.incquery.vedl.ui.AbstractEdlUiModule {
	public EdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
