/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.cep.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EventPatternLanguageRuntimeModule extends hu.bme.mit.incquery.cep.dsl.AbstractEventPatternLanguageRuntimeModule {

}
