/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.srct.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SrctUiModule extends hu.bme.mit.incquery.srct.ui.AbstractSrctUiModule {
	public SrctUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
