/**
 *
 * $Id$
 */
package hu.bme.mit.incquery.cep.metamodels.automaton.validation;

import hu.bme.mit.incquery.cep.metamodels.automaton.Automaton;
import hu.bme.mit.incquery.cep.metamodels.automaton.EventToken;

import hu.bme.mit.incquery.cep.metamodels.cep.Event;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link hu.bme.mit.incquery.cep.metamodels.automaton.InternalModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InternalModelValidator {
    boolean validate();

    boolean validateAutomata(EList<Automaton> value);
    boolean validateLatestEvent(Event value);
    boolean validateEventTokens(EList<EventToken> value);
}
