/**
 *
 * $Id$
 */
package hu.bme.mit.incquery.cep.metamodels.automaton.validation;

import hu.bme.mit.incquery.cep.metamodels.automaton.Guard;
import hu.bme.mit.incquery.cep.metamodels.automaton.State;

/**
 * A sample validator interface for {@link hu.bme.mit.incquery.cep.metamodels.automaton.Transition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransitionValidator {
    boolean validate();

    boolean validatePreState(State value);
    boolean validatePostState(State value);
    boolean validateGuard(Guard value);
}
