/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.srct.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import hu.bme.mit.incquery.srct.ui.internal.SrctActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SrctExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SrctActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SrctActivator.getInstance().getInjector(SrctActivator.HU_BME_MIT_INCQUERY_SRCT_SRCT);
	}
	
}
