/*
* generated by Xtext
*/
package hu.bme.mit.incquery.vedl.ui.contentassist;

import hu.bme.mit.incquery.vedl.ui.contentassist.AbstractEdlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EdlProposalProvider extends AbstractEdlProposalProvider {

}
