/*
* generated by Xtext
*/
package hu.bme.mit.incquery.srct.ui.contentassist;

import hu.bme.mit.incquery.srct.ui.contentassist.AbstractSrctProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SrctProposalProvider extends AbstractSrctProposalProvider {

}
