/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.cep.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EventPatternLanguageUiModule extends hu.bme.mit.incquery.cep.dsl.ui.AbstractEventPatternLanguageUiModule {
	public EventPatternLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
