/*
* generated by Xtext
*/
package hu.bme.mit.incquery.srct.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SrctOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
