<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="internalsm" nsURI="sm.meta" nsPrefix="hu.bme.mit.incquery.metamodels">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outTransitions" upperBound="-1"
        eType="#//Transition" containment="true" eOpposite="#//Transition/preState">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="wildcards" value=""/>
        <details key="name" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inTransitions" upperBound="-1"
        eType="#//Transition" eOpposite="#//Transition/postState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTokens" upperBound="-1"
        eType="#//EventToken" eOpposite="#//EventToken/currentState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startConstraints" upperBound="-1"
        eType="#//TimeConstraint" eOpposite="#//TimeConstraint/startState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stopConstraints" upperBound="-1"
        eType="#//TimeConstraint" eOpposite="#//TimeConstraint/stopState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediateConstraints"
        eType="#//TimeConstraint" eOpposite="#//TimeConstraint/intermediateState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preState" lowerBound="1"
        eType="#//State" eOpposite="#//State/outTransitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="#//Guard"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postState" lowerBound="1"
        eType="#//State" eOpposite="#//State/inTransitions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeConstraint" eType="#//TimeConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="TrapState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventPattern" lowerBound="1"
        eType="ecore:EClass CEPMeta.ecore#//EventPattern" eOpposite="CEPMeta.ecore#//EventPattern/stateMachines"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalExecutionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachines" upperBound="-1"
        eType="#//StateMachine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="latestEvent" eType="ecore:EClass CEPMeta.ecore#//Event"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentStateVisitors" upperBound="-1"
        eType="#//EventToken" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="msgToLog" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventToken">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//State"
        eOpposite="#//State/eventTokens"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventCollection" eType="#//EventCollection"
        containment="true" eOpposite="#//EventCollection/currentStateVisitor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventCollection" abstract="true">
    <eOperations name="getRecordedEvents" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eOperations name="addEvent" lowerBound="1">
      <eParameters name="event" eType="ecore:EClass CEPMeta.ecore#//Event"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentStateVisitor" lowerBound="1"
        eType="#//EventToken" eOpposite="#//EventToken/eventCollection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startState" lowerBound="1"
        eType="#//State" eOpposite="#//State/startConstraints"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stopState" lowerBound="1"
        eType="#//State" eOpposite="#//State/stopConstraints"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTimeStamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopTimeStamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intermediateState" eType="#//State"
        eOpposite="#//State/intermediateConstraints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumericCompareOperator">
    <eLiterals name="LESS_THAN" literal="LESS_THAN"/>
    <eLiterals name="LESS_OR_EQUALS" value="1"/>
    <eLiterals name="EQUALS" value="2"/>
    <eLiterals name="MORE_OR_EQUALS" value="3"/>
    <eLiterals name="MORE_THAN" value="4"/>
  </eClassifiers>
</ecore:EPackage>
