/*
 * generated by Xtext
 */
package hu.bme.mit.incquery.vedl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EdlRuntimeModule extends hu.bme.mit.incquery.vedl.AbstractEdlRuntimeModule {

}
