/*
* generated by Xtext
*/
package hu.bme.mit.incquery.cep.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EventPatternLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return hu.bme.mit.incquery.cep.dsl.ui.internal.EventPatternLanguageActivator.getInstance().getInjector("hu.bme.mit.incquery.cep.dsl.EventPatternLanguage");
	}
	
}
