/*
* generated by Xtext
*/
package hu.bme.mit.incquery.srct.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SrctAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/incquery/srct/parser/antlr/internal/InternalSrct.tokens");
	}
}
