/*
* generated by Xtext
*/
package hu.bme.mit.incquery.vedl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EdlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return hu.bme.mit.incquery.vedl.ui.internal.EdlActivator.getInstance().getInjector("hu.bme.mit.incquery.vedl.Edl");
	}
	
}
